package:
  name: parachute
  version: "0.0.0.2026.07.26"

source:
  git: https://codeberg.org/shinmera/parachute.git
  rev: c704a926ac215a25364a36b5e1ca73473864e7e3
  submodules: false

build:
  noarch: generic
  script:
    - DEST="$PREFIX/common-lisp/parachute"
    - mkdir -p "$DEST"
    - cp -r . "$DEST/"
    - rm -rf "$DEST/.git"

requirements:
  run:
    - cl-asdf
    - documentation-utils
    - trivial-custom-debugger
    - form-fiddle

tests:
  - script:
      - sbcl --no-userinit --non-interactive
          --eval '(require :asdf)'
          --eval '(asdf:load-system "parachute")'
          --eval '(asdf:test-system "parachute")'
    requirements:
      run:
        - sbcl

about:
  repository: https://codeberg.org/shinmera/parachute.git
  documentation: https://shinmera.com/docs/parachute/
  license: Zlib
  summary: An extensible and cross-compatible testing framework for Common Lisp.
  description: |
    Parachute is a simple-to-use and extensible testing framework for Common Lisp.

    See the [documentation](https://shinmera.com/docs/parachute/) for more details.
