package:
  name: trivial-custom-debugger
  version: "0.0.0.2023.08.14"

source:
  git: https://github.com/phoe/trivial-custom-debugger.git
  rev: 802473c75d9db625b8f37b05c95dde47b67c52fa
  submodules: false

build:
  noarch: generic
  script:
    - DEST="$PREFIX/common-lisp/trivial-custom-debugger"
    - mkdir -p "$DEST"
    - cp -r . "$DEST/"
    - rm -rf "$DEST/.git"

requirements:
  run:
    - sbcl
    - cl-asdf

tests:
  - script:
      - sbcl --no-userinit --non-interactive
          --eval '(require :asdf)'
          --eval '(asdf:load-system "trivial-custom-debugger")'
          --eval '(asdf:test-system "trivial-custom-debugger")'
    requirements:
      run:
        - parachute

about:
  repository: https://github.com/phoe/trivial-custom-debugger.git
  documentation: https://github.com/phoe/trivial-custom-debugger/blob/master/README.md
  license: BSD-2-Clause
  summary: Allows arbitrary functions to become the standard Common Lisp debugger
  description: |
    This is a portability library that allows one to fully override the standard debugger provided by their Common Lisp system for situations where binding `*debugger-hook*` is not enough - most notably, for `#'break`.

    See the [documentation](https://github.com/phoe/trivial-custom-debugger/blob/master/README.md) for more details.
